import 'Localize.dart';

class EN {
  static Map<String, String> Lang() {
    return {
      Localize.cancel: "Cancel",
      Localize.done: "Done",
      Localize.home: "Home",
      Localize.tutorials_title1: "Hire better\ntech talent, faster.",
      Localize.tutorials_title2: "Trusted to make recruiting\nfaster and easier",
      Localize.tutorials_title3: "View relevant\ncandidates & connect",
      Localize.tutorials_desc1: "Looking to hire? The candidates on Hired are\nqualified and ready to interview.",
      Localize.tutorials_desc2: "Innovative companies are only\nas successful as their people",
      Localize.tutorials_desc3: "Get instant access to a curated pool of\nresponsive top tech talent actively\nseeking their next role",
      Localize.password: "Password",
      Localize.signup: "Sign Up",
      Localize.signin: "Sign In",
      Localize.forgot_password_desc: "Enter your registered email below\nto receive password reset instruction",
      Localize.forgot_password: "Forgot Password",
      Localize.send: "Send",
      Localize.email: "Email",
      Localize.remember_password: "Remember password?",
      Localize.companyname: "Company Name",
      Localize.website_optional: "Website (Optional)",
      Localize.bytap: "By tapping, you agree to our ",
      Localize.termsandcondition: "Terms and Conditions.",
      Localize.getStarted: "Get Started",
      Localize.forgotPass: "Forgot Password?",
      Localize.continueSignin: "Continue",
      Localize.email_sent_title: "Email has been sent!",
      Localize.email_sent_desc:"Please check you inbox and click in the\nreceived link to reset  a password",
      Localize.reset_password: "Reset password",
      Localize.old_password: "Old password",
      Localize.new_password: "New password",
      Localize.confirm_password: "Confirm password",
      Localize.reset: "Reset",

      //Complete Profile
      Localize.complete_profile: "Complete Profile",
      Localize.welcome: "Welcome",
      Localize.upload_logo: "Upload logo",
      Localize.upload_logo_desc: "Keep your company looking sharp by\nuploading a logo to represent you on\nHire+",
      Localize.next: "Next",
      Localize.about_company: "About Company",
      Localize.industry_type: "Industry type",
      Localize.location: "Location",
      Localize.work_type: "Work type",
      Localize.benefits: "Benefits",
      Localize.well_done: "Well Done.!",
      Localize.profile_setup_completed:"You have Successfully completed\nyour details",
      Localize.go_to_home: "Go to Home",
      Localize.selectUploadLogo: "Please upload Logo",
      Localize.enterAboutCompany: "Please enter about company",
      Localize.selectIndustryType: "Please select Industry type",
      Localize.selectLocation: "Please select Location",
      Localize.selectWorkType: "Please select Work type",
      Localize.enterBenefits: "Please enter the benefits",
      Localize.update: "Update",
      Localize.resend: "Resend",

      //Chat
      Localize.chat: "Chat",

      //Account
      Localize.account: "Account",
      Localize.general: "General",
      Localize.edit_account: "Edit Account",
      Localize.manage_proposal: "Manage Proposal",
      Localize.bookmark_candidate: "Bookmark Candidate",
      Localize.change_password: "Change Password",
      Localize.help: "Help",
      Localize.terms_and_condition: "Terms & Conditions",
      Localize.privacy_policy: "Privacy Policies",
      Localize.about_us: "About Us",
      Localize.logout: "Logout",
      Localize.selectAnyItem: "Please select atleast one item",
      Localize.sessionTimeout: "Session Expired",
      Localize.sessionTimeoutMsg:"Sorry! Your session is expired, Please login again!",
      Localize.no_data_found: "No data found!",
      Localize.type_a_message: "Type a message",
      Localize.enterOldPassword: "Please enter old password",
      Localize.enterNewPassword: "Please enter new password",
      Localize.enterConfirmPassword: "Please enter confirm password",
      Localize.validateNewPassword: "New password must contain atleast 1 upper case, 1 lower case, 1 digit, 1 special character and atleast 8 characters long",
      Localize.validateNewAndConfirmPassword:"New password and confirm password does not match",
      Localize.notification: "Notification",
      Localize.verified: "Verified",
      Localize.deleteAccount: "Delete Account",
      Localize.deleteAccountMsg: "Are you sure you want to delete your account?",

      //Find People
      Localize.find_people: "Find people",
      Localize.filter_by: "Filter by ",
      Localize.search: "Search",
      Localize.search_caption: "Search by Job Title, Company name, Skills & more...",
      Localize.select_candidate: "Select Candidate",
      Localize.not_disclosed: "Not disclosed",
      Localize.salary: "Salary",
      Localize.preferred: "Preferred",
      Localize.like: "Like",
      Localize.liked: "Liked",

      //Proposal
      Localize.new_proposal: "New proposal",
      Localize.job_title: "Job title",
      Localize.contract_type: "Contract type",
      Localize.pay_scale: "Pay scale",
      Localize.pay_scale_per_month: "Pay scale (per month)",
      Localize.description: "Description",
      Localize.preview: "Preview",
      Localize.selectFromTemplate: "Select from template",
      Localize.details: "Details",

      //logout
      Localize.logoutMsg: "Are you sure you want to logout?",
      Localize.noThanks: "No Thanks!",

      //SignIn
      Localize.enterEmail: "Please enter email",
      Localize.enterPassword: "Please enter password",
      Localize.validateEmail: "Please enter valid email",
      Localize.validatePassword: "Password must contain atleast 1 upper case, 1 lower case, 1 digit, 1 special character and atleast 8 characters long",

      //SignUp
      Localize.enterCompanyName: "Please enter company name",
      Localize.validateWebsite: "Please enter the company website. Ex: https://www.hireplus.app",

      //Home Screen
      Localize.stats: "Stats",
      Localize.proposals_sent: "Proposals Sent",
      Localize.candidates_liked: "Candidates Liked",
      Localize.recent_proposal: "Recent Proposal",
      Localize.view_all: "View All",

      //New Proposal
      Localize.enterJobTitle: "Please enter Job title",
      Localize.selectContractType: "Please select Contract type",
      Localize.enterPayScale: "Please enter Pay scale",
      Localize.enterDescription: "Please enter description",
      Localize.selectCandidates: "Please select candidates",
      Localize.all: "All",
      Localize.bookmark: "Bookmark",
      Localize.bookmarked: "Bookmarked",
      Localize.candidate: "Candidate",
      Localize.delete: "Delete",
      Localize.delete_msg: "Are you sure you want to delete?",

      //Candidate details
      Localize.send_proposal: "Send Proposal",
      Localize.new_str: "New",
      Localize.download_cv: "Download CV",
      Localize.employment: "Employment",
      Localize.skills: "Skills",
      Localize.areas_of_interests: "Areas of interests",
      Localize.work_preferences: "Work preferences",
      Localize.preferred_work_location: "Preferred work location",
      Localize.notice_period: "Notice period",
      Localize.qualifications: "Qualifications",
      Localize.basic_details: "Basic Details",

      //Enums
      Localize.employee: "Employee",
      Localize.worker: "Worker",
      Localize.self_employed: "Self-employed",
      Localize.male: "Male",
      Localize.female: "Female",
      Localize.other: "Other",
      Localize.pending: "Pending",
      Localize.accepted: "Accepted",
      Localize.not_interested: "Not Interested",
      Localize.immediate: "Immediate",
      Localize.in_a_week: "In a Week",
      Localize.month1: "1 Month",
      Localize.months2: "2 Months",

      Localize.beginner: "Beginner",
      Localize.intermediate: "Intermediate",
      Localize.expert: "Expert",

      Localize.photo_library: "Photo Library",
      Localize.camera: "Camera",
      Localize.experience: "Experience",
      Localize.years: " Years",

      Localize.justNow: "Just now",
      Localize.oneMinAgo: "1 minute ago",
      Localize.oneHourAgo: "1 hour ago",
      Localize.oneDayAgo: "1 day ago",
      Localize.oneWeekAgo: "1 week ago",
      Localize.oneMonthAgo: "1 month ago",
      Localize.oneYearAgo: "1 year ago",
      Localize.secondsAgo: "seconds ago",
      Localize.minutesAgo: "minutes ago",
      Localize.hoursAgo: "hours ago",
      Localize.daysAgo: "days ago",
      Localize.weeksAgo: "weeks ago",
      Localize.monthsAgo: "months ago",
      Localize.yearsAgo: "years ago",
    };
  }
}
