import 'Localize.dart';

class PT {
  static Map<String, String> Lang() {
    return {
      Localize.cancel: "Cancelar",
      Localize.done: "Concluído",
      Localize.home: "Início",
      Localize.tutorials_title1: "Contrate melhores \ntalentos em tecnologia com mais rapidez.",
      Localize.tutorials_title2: "Confiável para tornar o recrutamento\nmais rápido e fácil",
      Localize.tutorials_title3: "Visualize candidatos\nrelevantes e conecte-se",
      Localize.tutorials_desc1: "Quer contratar? Os candidatos da Hired+ \nestão qualificados e prontos para uma entrevista.",
      Localize.tutorials_desc2: "Empresas inovadoras só têm sucesso com seu pessoal",
      Localize.tutorials_desc3: "Obtenha acesso instantâneo a um pool selecionado de talentos de tecnologia de ponta que procuram ativamente o seu próximo cargo",
      Localize.password: "Palavra-chave",
      Localize.signup: "Aderir",
      Localize.signin: "Entrar",
      Localize.forgot_password_desc: "Digite o seu e-mail registado abaixo para receber instruções de redefinição de senha",
      Localize.forgot_password: "Esqueci-me da palavra-chave?",
      Localize.send: "Enviar",
      Localize.email: "Email",
      Localize.remember_password: "Esqueci-me da palavra-chave?",
      Localize.companyname: "Nome da empresa",
      Localize.website_optional: "Website (Opcional)",
      Localize.bytap: "Ao submeter está a concordar com o nosso ",
      Localize.termsandcondition: "Termos e Condições",
      Localize.getStarted: "Iniciar",
      Localize.forgotPass: "Esqueci-me da palavra-chave?",
      Localize.continueSignin: "Continuar",
      Localize.email_sent_title: "O email foi enviado!",
      Localize.email_sent_desc:"PVerifique sua caixa de entrada e clique no link \nrecebido para redefinir uma senha",
      Localize.reset_password: "Alterar a palavra-chave",
      Localize.old_password: "Palavra-chave antiga",
      Localize.new_password: "Nova palavra-chave",
      Localize.confirm_password: "Confirmar palavra-chave",
      Localize.reset: "Alterar",

      //Complete Profile
      Localize.complete_profile: "Completar o perfil",
      Localize.welcome: "Bem-vindo",
      Localize.upload_logo: "Carregar logo",
      Localize.upload_logo_desc: "Mantenha a sua empresa sempre atualizada, enviando um logo para representá-lo no Hire+",
      Localize.next: "Próximo",
      Localize.about_company: "Sobre a empresa",
      Localize.industry_type: "Indústria",
      Localize.location: "Localização",
      Localize.work_type: "Tipo de trabalho",
      Localize.benefits: "Benefícios",
      Localize.well_done: "Parabéns",
      Localize.profile_setup_completed:"You Você completou com sucesso os seus detalhes",
      Localize.go_to_home: "Voltar ao início",
      Localize.selectUploadLogo: "Por favor carrega um logo",
      Localize.enterAboutCompany: "Por favor insira a descrição da empresa",
      Localize.selectIndustryType: "Por favor selecione uma indústria",
      Localize.selectLocation: "Por favor selecione uma localização",
      Localize.selectWorkType: "Por favor selecione o tipo de trabalho",
      Localize.enterBenefits: "Por favor insira os benefícios",
      Localize.update: "Atualizar",
      Localize.resend: "Reenviar",

      //Chat
      Localize.chat: "Chat",

      //Account
      Localize.account: "Conta",
      Localize.general: "Geral",
      Localize.edit_account: "Editar conta",
      Localize.manage_proposal: "Gerir proposta",
      Localize.bookmark_candidate: "Guardar candidato",
      Localize.change_password: "Alterar palavra-chave",
      Localize.help: "Ajuda",
      Localize.terms_and_condition: "Termos e condições",
      Localize.privacy_policy: "Políticas de privacidade",
      Localize.about_us: "Sobre nós",
      Localize.logout: "Sair",
      Localize.selectAnyItem: "Por favor selecione pelo menos 1 opção",
      Localize.sessionTimeout: "Sessão expirada",
      Localize.sessionTimeoutMsg:"Desculpe! A sua sessão expirou. Faça login novamente!",
      Localize.no_data_found: "Informação indisponível!",
      Localize.type_a_message: "Insira uma mensagem",
      Localize.enterOldPassword: "Por favor insira a palavra-chave antiga",
      Localize.enterNewPassword: "Por favor insira a nova palavra-chave",
      Localize.enterConfirmPassword: "Por favor confirma a palavra-chave",
      Localize.validateNewPassword: "A nova palavra-chave deve conter pelo menos 1 maiúscula 1 minúscula 1 dígito 1 caractere especial e pelo menos 8 caracteres",
      Localize.validateNewAndConfirmPassword:"New A nova palavra-chave e a confirmação da palavra-chave não correspondem",
      Localize.notification: "Notificação",
      Localize.verified: "Verificado",
      Localize.deleteAccount: "Remover conta",
      Localize.deleteAccountMsg: "Tem certeza que deseja remover sua conta?",

      //Find People
      Localize.find_people: "Encontrar recursos",
      Localize.filter_by: "Filtrar por",
      Localize.search: "Pesquisar",
      Localize.search_caption: "Pesquise por Cargo, Nome da empresa, habilidades e muito mais...",
      Localize.select_candidate: "Selecionar um candidato",
      Localize.not_disclosed: "Não divulgado",
      Localize.salary: "Salário",
      Localize.preferred: "Preferência",
      Localize.like: "Like",
      Localize.liked: "Liked",

      //Proposal
      Localize.new_proposal: "Nova proposta",
      Localize.job_title: "Cargo",
      Localize.contract_type: "Contrato",
      Localize.pay_scale: "Escala de salário",
      Localize.pay_scale_per_month: "Escala de salário (mensal)",
      Localize.description: "Descrição",
      Localize.preview: "Pré visualizar",
      Localize.selectFromTemplate: "Selecionar template",
      Localize.details: "Detalhes",

      //logout
      Localize.logoutMsg: "Tem certeza que deseja sair?",
      Localize.noThanks: "Não, obrigado!",

      //SignIn
      Localize.enterEmail: "Por favor insira um email",
      Localize.enterPassword: "Por favor insira uma palavra-chave",
      Localize.validateEmail: "Por favor insira um email válido",
      Localize.validatePassword: "A palavra-chave deve conter pelo menos 1 maiúscula 1 minúscula 1 dígito 1 caractere especial e pelo menos 8 caracteres",

      //SignUp
      Localize.enterCompanyName: "Por favor insira o nome da empresa",
      Localize.validateWebsite: "Por favor insira o website. Ex: https://www.hireplus.app",

      //Home Screen
      Localize.stats: "Estatísticas",
      Localize.proposals_sent: "Propostas enviadas",
      Localize.candidates_liked: "Likes dos candidatos",
      Localize.recent_proposal: "Propostas recentes",
      Localize.view_all: "Ver todas",

      //New Proposal
      Localize.enterJobTitle: "Por favor insira o cargo",
      Localize.selectContractType: "Por favor selecione o tipo de contrato",
      Localize.enterPayScale: "Por favor insira a escala do salário",
      Localize.enterDescription: "Por favor insira a descrição",
      Localize.selectCandidates: "Por favor selecione candidatos",
      Localize.all: "Todos",
      Localize.bookmark: "Favoritos",
      Localize.bookmarked: "Favoritos",
      Localize.candidate: "Candidato",
      Localize.delete: "Remover",
      Localize.delete_msg: "Tem certeza de que deseja remover?",

      //Candidate details
      Localize.send_proposal: "Enviar proposta",
      Localize.new_str: "Novo",
      Localize.download_cv: "Descarregar CV",
      Localize.employment: "Emprego",
      Localize.skills: "competências",
      Localize.areas_of_interests: "Áreas de interesse",
      Localize.work_preferences: "Preferências laborais",
      Localize.preferred_work_location: "Localização do trabalho",
      Localize.notice_period: "Período de notificação",
      Localize.qualifications: "Qualificações",
      Localize.basic_details: "Detalhes base",

      //Enums
      Localize.employee: "Funcionário",
      Localize.worker: "Trabalhador",
      Localize.self_employed: "Trabalhador por conta própria",
      Localize.male: "Masculino",
      Localize.female: "Feminino",
      Localize.other: "Outro",
      Localize.pending: "Pendente",
      Localize.accepted: "Aceite",
      Localize.not_interested: "Não interessado",
      Localize.immediate: "Imediata",
      Localize.in_a_week: "Em uma semana",
      Localize.month1: "1 Mês",
      Localize.months2: "2 Meses",

      Localize.beginner: "Principiante",
      Localize.intermediate: "Intermédio",
      Localize.expert: "Especialista",

      Localize.photo_library: "Biblioteca de fotografias",
      Localize.camera: "Camera",
      Localize.experience: "Experiência",
      Localize.years: " Anos",

      Localize.justNow: "Agora mesmo",
      Localize.oneMinAgo: "1 minuto atrás",
      Localize.oneHourAgo: "1 hora atrás",
      Localize.oneDayAgo: "1 dia atrás",
      Localize.oneWeekAgo: "1 semana atrás",
      Localize.oneMonthAgo: "1 mês atrás",
      Localize.oneYearAgo: "1 ano atrás",
      Localize.secondsAgo: "segundos atrás",
      Localize.minutesAgo: "minutos atrás",
      Localize.hoursAgo: "horas atrás",
      Localize.daysAgo: "dias atrás",
      Localize.weeksAgo: "semanas atrás",
      Localize.monthsAgo: "meses antes",
      Localize.yearsAgo: "anos atrás",
    };
  }
}
